### ISSUE TITLE
Exception when trying to start operate

### ISSUE THREAD

**Issue by akkie** [zeebe-io/zeebe-docker-compose#36]
I get the following exception when I try to start operate:

```
zeebe_1          | Caused by: java.lang.ClassNotFoundException: io.zeebe.exporter.ElasticsearchExporter
zeebe_1          |      at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
zeebe_1          |      at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[?:?]
zeebe_1          |      at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
zeebe_1          |      at io.camunda.zeebe.broker.exporter.repo.ExporterRepository.load(ExporterRepository.java:78) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe_1          |      at io.camunda.zeebe.broker.Broker.buildExporterRepository(Broker.java:435) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe_1          |      at io.camunda.zeebe.broker.Broker.lambda$partitionsStep$21(Broker.java:408) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe_1          |      at io.camunda.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:63) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe_1          |      at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe_1          |      at io.camunda.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:61) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe_1          |      at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe_1          |      at io.camunda.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:46) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe_1          |      at io.camunda.zeebe.broker.Broker.partitionsStep(Broker.java:423) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe_1          |      at io.camunda.zeebe.broker.Broker.lambda$initStart$10(Broker.java:234) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe_1          |      at io.camunda.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:63) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe_1          |      at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe_1          |      at io.camunda.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:61) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe_1          |      at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe_1          |      at io.camunda.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:46) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe_1          |      at io.camunda.zeebe.broker.Broker.internalStart(Broker.java:180) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe_1          |      at io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) ~[zeebe-util-1.0.0.jar:1.0.0]
zeebe_1          |      at io.camunda.zeebe.broker.Broker.start(Broker.java:160) ~[zeebe-broker-1.0.0.jar:1.0.0]
zeebe_1          |      at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:60) ~[camunda-cloud-zeebe-1.0.0.jar:1.0.0]
zeebe_1          |      at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:819) ~[spring-boot-2.4.5.jar:2.4.5]
zeebe_1          |      ... 5 more
zeebe_1          | 2021-05-18 06:28:30.783 [] [main] INFO
zeebe_1          |       org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor - Shutting down ExecutorService 'applicationTaskExecutor'
operate_1        | 2021-05-18 06:28:31.691  WARN 7 --- [           main] i.c.o.u.RetryOperation                   : method [HEAD], host [http://elasticsearch:9200], URI [/_index_template/operate_template?master_timeout=30s], status line [HTTP/1.1 405 Method Not Allowed]
operate_zeebe_1 exited with code 1
```

I use the latest master.

**Comment by domaroff** [comment]
I have it too. After some investigation I found that class name for exporter in  ZeeBe application.yaml should be 'io.camunda.zeebe.exporter.ElasticsearchExporter' instead of 'io.zeebe.exporter.ElasticsearchExporter'.

**Comment by akkie** [comment]
@domaroff Please see https://github.com/zeebe-io/zeebe-docker-compose/pull/37 for a working solution
